
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cupons_php
    volumes:
      - ./:/var/www
    networks:
      - cupons-network

  nginx:
    image: nginx:latest
    container_name: cupons_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - cupons-network

  mysql:
    image: mysql:8.0
    container_name: cupons_mysql
    restart: always
    environment:
      MYSQL_DATABASE: cupons
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: thiago
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cupons-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cupons_phpmyadmin
    environment:
      PMA_HOST: cupons_mysql
      PMA_USER: thiago
      PMA_PASSWORD: 123456
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - cupons-network

  migrator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cupons_migrator
    depends_on:
      - mysql
      - php
    volumes:
      - .:/var/www
    command: ["php", "/var/www/run-migration.php"]
    networks:
      - cupons-network

volumes:
  dbdata:

networks:
  cupons-network:
    driver: bridge
